name: flutter_pokedex
description: PokedexApp
publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  get_it: ^7.1.3
  rxdart: ^0.27.7
  lottie: ^2.2.0
  flutter_svg: ^1.0.3
  path_provider: ^2.0.5
  shared_preferences: ^2.0.7
  cached_network_image: ^3.1.0
  infinite_scroll_pagination: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  audioplayers: ^4.1.0
  audio_video_progress_bar: ^1.0.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  firebase_crashlytics: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/pokemons_types/
    - assets/images/technical_records_types/
    - assets/images/technical_machines_types/
    - assets/images/pokemons_generations/generation_1/
    - assets/images/pokemons_generations/generation_2/
    - assets/images/pokemons_generations/generation_3/
    - assets/images/pokemons_generations/generation_4/
    - assets/images/pokemons_generations/generation_5/
    - assets/images/pokemons_generations/generation_6/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_7/
    - assets/images/pokemons_generations/generation_8/
    - assets/lotties/
    

  fonts:
    - family: CircularStd-Book
      fonts:
        - asset: assets/fonts/CircularStd-Book.otf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/app_icon.png"

flutter_native_splash:
  image: "assets/images/splash_logo.png"
  color: "#ffffff"