// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbfFyFq9doUsuuOO4Ym3cMNQkYeJ-qZxI',
    appId: '1:724202841407:web:4d1255d5e539e761dc1f8a',
    messagingSenderId: '724202841407',
    projectId: 'ducpv-pokedex',
    authDomain: 'ducpv-pokedex.firebaseapp.com',
    storageBucket: 'ducpv-pokedex.appspot.com',
    measurementId: 'G-VXSV3YVF3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuD9rQAW8CRKrwh4A1H4-AEOUj10rPKSw',
    appId: '1:724202841407:android:3de747c2e8a512c6dc1f8a',
    messagingSenderId: '724202841407',
    projectId: 'ducpv-pokedex',
    storageBucket: 'ducpv-pokedex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA_ykdpxM2x6SXu8_l_vAW3mPlkkbtmNM',
    appId: '1:724202841407:ios:31dd038286870581dc1f8a',
    messagingSenderId: '724202841407',
    projectId: 'ducpv-pokedex',
    storageBucket: 'ducpv-pokedex.appspot.com',
    iosClientId: '724202841407-1njjmbn1nmvuouenqbcamgch3k21ol8r.apps.googleusercontent.com',
    iosBundleId: 'com.ducpv.flutterPokedex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA_ykdpxM2x6SXu8_l_vAW3mPlkkbtmNM',
    appId: '1:724202841407:ios:31dd038286870581dc1f8a',
    messagingSenderId: '724202841407',
    projectId: 'ducpv-pokedex',
    storageBucket: 'ducpv-pokedex.appspot.com',
    iosClientId: '724202841407-1njjmbn1nmvuouenqbcamgch3k21ol8r.apps.googleusercontent.com',
    iosBundleId: 'com.ducpv.flutterPokedex',
  );
}
