name: Action Build & Upload APK to FirebaseAppDistribution
on:
  push:
    branches: [ master ]

jobs:
  build_and_upload_to_firebase:
    name: Build & Upload APK to FirebaseAppDistribution
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.1'
      
      - name: Checkout SourceCode
        uses: actions/checkout@v2
      
      - name: Get Dependencies
        run: flutter pub get
      
      - name: Build Release APK
        run: flutter build apk --release
      
      - name: Upload APK to FirebaseAppDistribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          file: build/app/outputs/flutter-apk/app-release.apk
          groups: poke-man